# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('time', models.DateField(default=datetime.datetime(2016, 11, 4, 23, 51, 19, 88631, tzinfo=utc))),
                ('username', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=250)),
                ('lyrics', models.TextField(max_length=3000)),
                ('beat', models.FileField(upload_to=b'')),
                ('story', models.TextField(max_length=2000)),
                ('photos', models.ImageField(upload_to=b'')),
            ],
        ),
    ]
