# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 00:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pushmodule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='beat',
            field=models.FileField(blank=None, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='create',
            name='photos',
            field=models.ImageField(blank=None, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='create',
            name='time',
            field=models.DateField(default=datetime.datetime(2016, 11, 5, 0, 10, 14, 449413, tzinfo=utc)),
        ),
    ]
