# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushmodule', '0005_create_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='filter',
            field=models.IntegerField(choices=[(1, 'Art Punk'), (2, 'Alternative Rock'), (3, 'College Rock'), (4, 'Cross Over Thras'), (5, 'Crust Punk'), (6, 'Experimental Rock'), (7, 'Hard Core Punk'), (8, 'Acoustic Blues'), (9, 'Indie Rock'), (10, 'Chamber Music')], default=1),
        ),
    ]
