# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushmodule', '0006_auto_20161105_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='beat',
            field=models.FileField(blank=None, default=None, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='create',
            name='photos',
            field=models.ImageField(blank=None, default=None, null=True, upload_to=b''),
        ),
    ]
