# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pushmodule', '0007_auto_20161105_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='create',
            old_name='filter',
            new_name='filter_genre',
        ),
        migrations.AddField(
            model_name='create',
            name='filter_mood',
            field=models.IntegerField(choices=[(1, 'Joy'), (2, 'Sad'), (3, 'Serenity'), (4, 'Trust'), (5, 'Anger'), (6, 'Disgust'), (7, 'Boredum'), (8, 'Surprise'), (9, 'Fear'), (10, 'Vigilance')], default=1),
        ),
    ]
